# Site settings
title: "Krunal Kapadiya"
email: krunalkapadiya3894@gmail.com
description: "Google Certified Associate Android Developer"
baseurl: ""
url: "http://krunal3kapadiya.com/"
title_description: "Krunal Kapadiya Android Developer"
title_image: "https://gravatar.com/avatar/b1a1cc3d71600c6e47c33c65fa08f71f?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: krunal3kapadiya  
github_repository: https://github.com/krunal3kapadiya/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: krunal3kapadiya
github_username:  krunal3kapadiya
instagram_username: krunal3kapadiya
reddit_username: krunal3kapadiya
linkedin_link: https://www.linkedin.com/in/krunal3kapadiya
google_plus_link: https://plus.google.com/105781963540070657302
stackoverflow_link: https://stackoverflow.com/users/5255006/krunal-kapadiya
facebook_link: https://www.facebook.com/krunal3kapadiya
medium_link: https://medium.com/@krunal3kapadiya

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/krunal3kapadiya\">Krunal Kapadiya</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/krunal3kapadiya/krunal3kapadiya.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
