baseURL = "https://krunal3kapadiya.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Krunal Kapadiya"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "krunal3kapadiya"

# Google Analytics
#googleAnalytics = "UA-177449251-1"

[params]
title = "I'm Krunal Kapadiya"
author = "Krunal Kapadiya"
description = "Call me KK"
profilePicture = "images/profile.jpg"
keywords = "krunal3kapadiya, Krunal Kapadiya, Android developer, DataScience, Data-Science"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/krunal3kapadiya"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/krunal3kapadiya"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/krunal3kapadiya"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:krunal3kapadiya@gmail.com"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"